version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ruraldb
      POSTGRES_USER: ruraluser
      POSTGRES_PASSWORD: ruralpass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://ruraluser:ruralpass@db:5432/ruraldb
      NODE_ENV: production
    ports:
      - "3000:3000"
    command: >
      sh -c "npx prisma migrate deploy && npm run start:prod"

volumes:
  db_data: